---
abstract: ~
author:
  - 'Takumi Akiyama <t.akiym at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Tacochan
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Plack::Builder::Conditionals: 0
  Plack::Middleware::ReverseProxy: 0
  Skype::Any: 0.03
  Twiggy: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/akiym/p5-App-Tacochan.git
version: 0.02
